version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  linux:
    docker:
      - image: ubuntu:rolling

    resource_class: large
    steps:
      - checkout

      - run:
          command: |
            apt-get update
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -q -y curl g++ zlib1g-dev patch python3 python3-pip python3-distutils python-is-python3
            curl -sSL https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64 >/usr/local/bin/bazel
            chmod +x /usr/local/bin/bazel
            python3 -m pip install pip-tools

      - run:
          command: |
            ./exercise.sh

  windows:
    executor:
      name: win/default
      shell: powershell.exe
      size: large
    steps:
      - checkout

      - run:
          shell: cmd.exe
          command: |
            curl -sSL https://github.com/bazelbuild/bazel/releases/download/5.1.1/bazel-5.1.1-windows-x86_64.exe >/ProgramData/nvm/bazel.exe
            # python and pip-tools already present in Circle CI's Windows environment.

      - run:
          command: |
            cd 06-python
            # TODO Check if there is still a problem with Python-Gazelle and Windows:
            bazel build "..."
            bazel run //app:app_bin

workflows:
  version: 2
  both_platforms:
    jobs:
      - linux
      - windows
